# -*-Python-*-

cc_library(name = "lines",
           srcs = ["lines.c", "data.c"],
           hdrs = ["lines.h", "data.h"],
           deps = ["//:bkstyle"],
           visibility = ["//visibility:public"]
           )
