# -*-Python-*-

cc_library(name = "utils",
           srcs = ["base64.c", "webencode.c"],
           hdrs = ["base64.h", "webencode.h"],
           deps = ["//:bkstyle", "//lines:lines"],
           visibility = ["//visibility:public"]
           )
